cap erase tempRWA.dta
cap erase enemy_DRCgov.dta
cap erase bilateral_reconciliation_plusSD.dta
cap erase obs_share.dta
cap erase KeyPlayerplusSD.dta
cap erase hutu_tutsi_alliances_simul.dta
cap erase hutu_tutsi_neutral_simul.dta
cap erase temp_hutu_tutsi.dta
cap erase temp_struc_cov.dta
cap erase trash.dta
cap erase trash_d.dta
cap erase MC_merging_key_d.dta
cap erase temp_bench_dyadic.dta
cap erase bilateral_reconciliation_minusSD.dta
cap erase KeyPlayerminusSD.dta	
cap erase acled_KRTZ_identifiers.dta
cap erase KPresult.dta
cap erase Foreign_KPresult.dta
cap erase avgbench_data.dta
cap erase MC_merging_key.dta
cap erase bench_data.dta
cap erase bench_simul.dta
cap erase bench_aminus.dta
cap erase bench_aplus.dta
cap erase temp_counterfactual.dta
cap erase simul.dta
cap erase temp.dta
cap erase temp_aplus.dta
cap erase temp_aminus.dta
cap erase temp_MC.dta
cap erase avgbench_simul.dta
cap erase aminus_ref.dta
cap erase aplus_ref.dta
cap erase temp_MC.dta
cap erase avgbench_simul.dta
cap erase aminus_ref.dta
cap erase aplus_ref.dta
cap erase acled_KRTZ_identifiers.dta
cap erase KPresult.dta
cap erase Foreign_KPresult.dta
cap erase avgbench_data.dta
cap erase MC_merging_key.dta
cap erase bench_data.dta
cap erase bench_simul.dta
cap erase bench_aminus.dta
cap erase bench_aplus.dta
cap erase temp_counterfactual.dta
cap erase simul.dta
cap erase temp.dta
cap erase temp_aplus.dta
cap erase temp_aminus.dta
cap erase temp_MC.dta
cap erase avgbench_simul.dta
cap erase aminus_ref.dta
cap erase aplus_ref.dta
cap erase rank_links.dta
cap erase temp_rain.dta
cap erase temp_counterfactual.dta
cap erase zero_simul.dta 
cap erase all_neutral_simul.dta
cap erase all_friends_simul.dta
cap erase no_enemies_simul.dta
cap erase temp_bench_aminus.dta
cap erase name_merge
cap erase name_merge_d
cap erase KPcounter_simul.dta
cap erase remove_link_counter_simul.dta
cap erase acled_KRTZ_identifiers.dta
cap erase KPresult.dta
cap erase Foreign_KPresult.dta
cap erase avgbench_data.dta
cap erase MC_merging_key.dta
cap erase bench_data.dta
cap erase bench_simul.dta
cap erase bench_aminus.dta
cap erase bench_aplus.dta
cap erase temp_counterfactual.dta
cap erase simul.dta
cap erase temp.dta
cap erase temp_d.dta
cap erase temp_aplus.dta
cap erase temp_aminus.dta
cap erase temp_MC.dta
cap erase avgbench_simul.dta
cap erase aminus_ref.dta
cap erase aplus_ref.dta
cap erase name_merge.dta
cap erase name_merge_d.dta
cap erase KPcounter_simul_1.dta
cap erase no_friends_simul.dta
cap erase temp_bench_aminus.dta
cap erase temp_bench_aplus.dta
cap erase temp_gov.dta
cap erase temp_gov_d.dta
cap erase temp_name.dta
cap erase temp_name_d.dta
cap erase tempRWA.dta
cap erase acled_KRTZ_identifiers.dta
cap erase aminus_ref.dta
cap erase aplus_ref.dta
cap erase avgbench_data.dta
cap erase avgbench_simul.dta
cap erase bench_aminus.dta
cap erase bench_aplus.dta
cap erase bench_data.dta
cap erase counter_proba.dta
cap erase csf_surplus.dta
cap erase d_neighbor.dta
cap erase endo_KP_all_equilibria.dta
cap erase endo_KPresult.dta
cap erase endo_KPresult__Large_Groups.dta
cap erase endo_KPresult_FDLR_INTER_HUTU.dta
cap erase endo_KPresult_foreign.dta
cap erase endo_KPresult_Ituri.dta
cap erase endo_KPresult_RCD_UG_RWA.dta
cap erase endo_network_rewiring.dta
cap erase endo_network_rewiring_stat_KP.dta
cap erase exo_KPresult_Large_Groups.dta
cap erase exo_KPresult_FDLR_INTER_HUTU.dta
cap erase exo_KPresult_foreign.dta
cap erase exo_KPresult_Ituri.dta
cap erase exo_KPresult_RCD_UG_RWA.dta
cap erase Foreign_endo_KPresult.dta
cap erase Foreign_KPresult.dta
cap erase good_temp.dta
cap erase good_temp_d.dta
cap erase interior_condition_foreign.dta
cap erase MC_counter_network.dta
cap erase MC_draws.dta
cap erase MC_merging_key.dta
cap erase neighbor.dta
cap erase simul.dta
cap erase temp_active.dta
cap erase temp_active_d.dta
cap erase temp_aminus.dta
cap erase temp_aplus.dta
cap erase temp_baseline.dta
cap erase temp_counter.dta
cap erase temp_counterfactual.dta
cap erase temp_cov.dta
cap erase temp_goodness.dta
cap erase temp_id.dta
cap erase temp_MC.dta
cap erase temp_ncovariates.dta
cap erase temp_network.dta
cap erase temp_pred_rain.dta
cap erase temp_rain.dta
cap erase temp_struc_cov.dta
cap erase temp_structural_covariates.dta
cap erase temp_time_varying_network.dta
cap erase temp_window.dta
cap erase tempFig4.dta
cap erase trash.dta
cap erase trash_d.dta
cap erase endo_KeyPlayer_result.dta
cap erase endo_RCD_UG_RWA_Conditional.dta
cap erase endo_Large_Groups_Conditional.dta
cap erase endo_Ituri_Conditional.dta
cap erase endo_Foreign_Conditional.dta
cap erase endo_FDLR_INTER_HUTU_Conditional.dta
cap erase endo_KPresult_Large_Groups.dta
cap erase endo_KeyPlayer_result_Conditional.dta
cap erase endo_goodness.dta



